[package]
name = "CoreFoundation-sys"
version = "0.1.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
license = "MIT"

links = "CoreFoundation"
build = "build.rs"

[dependencies]
libc = "0.1.8"
